
- name: Start the MySQL service
  sudo: yes
  service:
    name: mysql
    state: started
    enabled: true

- name: Update mysql root password for all root accounts
  sudo: yes
  mysql_user:
    name: root
    host: "{{ item }}"
    password: root1234
    login_user: root
    login_password: root1234
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create Database
  mysql_db: name={{project_name}}_db encoding=utf8 login_user=root login_password=root1234 state=present

- name: Create user for database
  mysql_user: name=master password=master priv=*.*:ALL,GRANT login_user=root login_password=root1234 state=present
