- hosts: default
  vars:
    project_name: {{project_name}}
  tasks:
    - include: tasks/apt.yml
    - include: tasks/zsh.yml
    - include: tasks/pip.yml
    - include: tasks/stack.yml
    - include: tasks/database.yml
  handlers:
    - include: handlers/handlers.yml
